### ISSUE TITLE
WERKT NIET

### ISSUE THREAD

**Issue by Timmeehhh** [rjbrakel/TowerDefenceVSR#1]
Hallo jongens,

Dit is pure troep. Ga eens stoelen sjouwen voor je VSR.

IS GEWOON NIET GOED.

Groetjes, ook van Bets en de kids

Toedelssssssss 🌵

**Comment by dfwwasse** [comment]
Hallo Bets en de kids,

Hoe was de vakantie? Wij stellen jullie input zeer op prijs, maar moeten toch echt concluderen dat jullie poep praten.

Wij gaan gewoon deze simpele opdracht doen en dan zijn we er klaar mee.

Met vriendelijke groet,

Het feestteam en dirk
